# Generated by Django 4.2.10 on 2024-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='realizado',
        ),
        migrations.AddField(
            model_name='analisis',
            name='resultado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='realizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
